### PR TITLE
Change slug of basics concept exercise

### PR DESCRIPTION
**Pull request by mirkoperillo**
Currently all the Java concept exercises slugs are relative to one concept they want to present.
The general rule is that the slug of exercise should be relative to the story they implement.

I have trieds to apply this to the basics exercise.
Another detail: in this PR  I propose a name to the exercise (the missing `name` field in `config.json`)

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by mirkoperillo** [comment]
@ericbalawejder @msomji I need a review

**Review by msomji — APPROVED** [review]

**Comment by ericbalawejder** [comment]
https://github.com/exercism/docs/blob/main/anatomy/tracks/concept-exercises.md#file-metaconfigjson

I noticed the linter failure for `Array is empty: 'files.exemplar':`. I saw the docs from the Slack conversation earlier (posted above). Is it valuable to add the field `exemplar` at this time? 

Do we want to turn the linter off?

**Comment by mirkoperillo** [comment]
@ericbalawejder you are right.
In this PR I put all the steps needed to change an exercise slug.
The idea is to use this PR as a documentation example and I'm thinking to open a specific issue about the need to change the concept exercise slugs.

I think it's better to provide a unique PR about the linter checks referring to the relative issue.
I think it's better to maintain the linter on, because the linter rules are a work in progress.

**Comment by ericbalawejder** [comment]
Sounds good.

**Review by ericbalawejder — APPROVED** [review]

**Pull request merged**
