### PR TITLE
atbash-cipher: add hints about no starter implementation

### PR DESCRIPTION
**Pull request by anuran-Chakraborty**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sjwarner-bp** [comment]
Hi @anuran-Chakraborty, just wondering how you are getting on with this 🙂

**Comment by sjwarner-bp** [comment]
@exercism/java - we don't seem to have a policy on abandoned PRs, but what do we think of this one? :slightly_smiling_face:

It seems to have happened a couple of times recently!

**Comment by FridaTveit** [comment]
Yes, we have been a bit unlucky with that recently...

Not too much work has been done and this is a good first patch issue, so I'd be happy with just closing this and putting a comment on the issue saying that someone else can work on it. What do you think @sjwarner-bp? 🙂

**Comment by sjwarner-bp** [comment]
Sounds like a good plan to me :slightly_smiling_face:

**Pull request closed without merging**
