### PR TITLE
fix spelling mistake in exception message #745

### PR DESCRIPTION
**Pull request by riktimmondal**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by stkent** [comment]
No idea why that failed; I'll retry the build and 🤞!

**Comment by stkent** [comment]
Ah, whoops, I see why the tests failed now! The change you correctly made was in a test assertion, but the example solution used to validate these tests is still using the _old_ (incorrect) string. If you look in the file

```
exercises/largest-series-product/src/example/java/LargestSeriesProductCalculator.java
```

you should find another copy of the incorrect string `"String to search may only contains digits."`. If you fix that one too, and push up a new or modified commit, then I think we should be good :)

**Comment by riktimmondal** [comment]
Ok

**Comment by riktimmondal** [comment]
I push a new commit correcting the other file then also the build has failed.Please have a look at it

**Comment by stkent** [comment]
@riktimmondal you appear to have pushed an unrelated commit to the branch upon which this pull request is based:

```
82e48fe Added angular bracket when calling constructor
```

This new commit is unrelated and so would ideally not be part of this PR. It's also what is _now_ causing the build to fail; there's a stray `s` character in the change that means the binary search tree tests are now failing to compile. The ideal path forward would be to:

1) Make a new branch based on master
2) Cherry-pick the two commits relevant to issue #745 (cd07493 and d5966bd)
3) Push that new branch to your fork of this repository
4) Make a new pull request based on that newly-pushed branch

I see that you have now closed this pull request, so if you are no longer interested in resolving #745, that's no problem and we can take it from here. Totally your call :)

**Pull request closed without merging**
