### PR TITLE
markdown: add to track

### PR DESCRIPTION
**Pull request by bmkiefer**
I implemented the markdown exercise because the java track did not yet have it. I am unsure where I should put this in the curriculum. I picked after word search because markdown parsing seemed like a similar skill set, but I am open to change it.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by bmkiefer** [comment]
A couple things here. 1) I am not entirely sure why this recent build is failing. 2) I realize that I didn't fully read this README.md. This exercise is centered around refactoring a solution to be cleaner and still allow the tests to pass. Does anyone have ideas for how to make my optimal solution better and what things I could do to my solution to make it worse for learners to clean up. A forward and backward direction haha

**Comment by sjwarner-bp** [comment]
It seems like the Travis build is failing with the same issue it had in #1004 - I'll restart the build and see what happens! This is very odd, but both of these times have been when new exercises were added... Maybe this is a clue?

(Sorry for the request Frida - misclicked! :scream: )

**Comment by sjwarner-bp** [comment]
Hmm... seems to have failed again for the same reasons (those seen in #1004 too).

```
+echo ==================================================
==================================================
+echo 'Solving settings.gradle'
Solving settings.gradle
+echo ==================================================
==================================================
+./exercism --config .journey-test.exercism.json fetch java settings.gradle
127.0.0.1 - - [30/Nov/2017:08:15:43 +0000] "GET /v2/exercises/java/settings.gradle HTTP/1.1" 200 339 0.0072
Not Submitted:         1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
New:                   1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
unchanged: 0, updated: 0, new: 1
+cp -R -H '/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*' /home/travis/build/exercism/java/build/exercism/java/settings.gradle/src/main/java/
cp: cannot stat ‘/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*’: Not a directory
```

I don't think any of the team have a clear idea of why this happens (but I'd rather not just keep clicking the restart button)!

**Comment by FridaTveit** [comment]
@stkent @Smarticles101 any ideas why the build failed?

**Comment by Smarticles101** [comment]
I'm going to push a change real quick. I think this could fix it [this](https://superuser.com/questions/1235420/cp-cannot-stat-some-path-no-such-file-or-directory)

**Comment by sjwarner-bp** [comment]
Hmm that does look very similar to what we're experiencing. Not sure why it only happens sometimes (unless it is to do with new exercises), but I'm excited to see if this works @Smarticles101 :+1:

**Comment by sjwarner-bp** [comment]
Still the same old...
```
+echo ==================================================
==================================================
+echo 'Solving settings.gradle'
Solving settings.gradle
+echo ==================================================
==================================================
+./exercism --config .journey-test.exercism.json fetch java settings.gradle
127.0.0.1 - - [30/Nov/2017:14:00:15 +0000] "GET /v2/exercises/java/settings.gradle HTTP/1.1" 200 339 0.0064
Not Submitted:         1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
New:                   1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
unchanged: 0, updated: 0, new: 1
+cp -R -H '/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*' /home/travis/build/exercism/java/build/exercism/java/settings.gradle/src/main/java/
cp: cannot stat ‘/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*’: Not a directory
```

**Comment by sjwarner-bp** [comment]
And once more :cry:

**Comment by Smarticles101** [comment]
Not really sure why it's still failing... perhaps we can summon someone more familiar with bash

**Comment by FridaTveit** [comment]
It looks like it thinks `settings.gradle` is an exercise:
```
solve_all_exercises(exercism_exercises_dir="/home/travis/build/exercism/java/build/exercism", exercism_configfile=".journey-test.exercism.json", exercise_to_solve="settings.gradle")
```

**Comment by Smarticles101** [comment]
Oh you're right @FridaTveit I see now

**Comment by FridaTveit** [comment]
Great, thanks @Smarticles101! Hopefully it'll work this time :)

**Comment by Smarticles101** [comment]
It's going to work this time but for a different reason... It's hit GitHub's API rate limit lol #772

**Comment by bmkiefer** [comment]
Awesome feedback guys, thank you! Also, good to know why that build was breaking. 

List of code issues that I added to the sample solution. let me know what you want to see or not.
1. removed some of code reuse
2. packed a lot of code into parse function
3. braces, spacing, and indentation is messed up in places
4. variable names and method names are unclear in places
5. using string concatenation in the main parse function instead of StringBuilder
6. remove break from header counter and added logic to for loop conditional
7. added unnecessary check to loops checking active lists

Making chaos was fun lol

Might be worth keeping these as notes for mentors somehow or maybe included as hints?

**Comment by sjwarner-bp** [comment]
Hi @bmkiefer - I am not sure what the others think about keeping track of this, but I think it could be a good idea to take that list and stick it into `.meta/hints.md`.

However, I am sure if this is not the ideal place to keep those notes then someone else might have a better idea! 🙂

**Comment by sjwarner-bp** [comment]
Ah - I didn't know these got appended to README.md @FridaTveit - thanks for letting me know that 🙂 In that case I'd suggest that they should be stored somewhere else, but probably in that `.meta` hidden folder?

As for CI fixes, I'd definitely open an issue and start fixes in a new PR to avoid noise - I'll open an issue now 🙂

**Comment by bmkiefer** [comment]
Okay, what would you like me to do with that CI fix commit? I am confident this fixes the issue, but there may be a better place in the scripts to fix it, if anyone has an opinion. This bug occurs when the settings gradle file changes, an exercise changes, and it doesnt hit the API limit on GitHub. It basically thinks that settings gradle is another exercise and has to be ignored when its walking through exercises to test. I didn't like moving it into another PR because you almost need a new exercise implemented to find it.

**Comment by FridaTveit** [comment]
Thanks for looking into that @bmkiefer :) I've been fixing that in a separate PR (#1064) since it doesn't relate to adding this new exercise. Just changing something in settings.gradle should cause the bug to show itself I think :) Feel free to review/suggest changes to that PR. I think all the CI changes that have been added to this PR should be reverted since they aren't related to this PR. It's always best to only deal with one issue in a PR. Otherwise it become hard to review and it makes the history messy.

Are you okay with that? Sorry for the confusion and adding lots of noise and additional problems to your PR! :)

**Comment by bmkiefer** [comment]
Yep, that is cool. I will revert the CI changes. Good teamwork!

**Comment by sjwarner-bp** [comment]
Great work everyone! That is one mystery fixed 🙂 

In regards to this PR @bmkiefer, I've seen you've undone the CI changes! That's great - I think this whole thing is ready to merge when we have added your list about all the code issues you have written!

**Comment by FridaTveit** [comment]
The PR with the fix has been merged now so if you merge/rebase on master then the build should hopefully be okay (fingers crossed!) :)

**Comment by bmkiefer** [comment]
I need to undo the earlier ones yet and we will have to do a squash commit here as well when this is merged given the reverts will be a little messy.

**Comment by FridaTveit** [comment]
Agreed, squash and merge should tidy it up :)

**Comment by bmkiefer** [comment]
Okay, now all the CI work done here is reverted! Woo

**Comment by bmkiefer** [comment]
Weird, it gave the commits new hashes after I rebased the change that you made on master.

**Comment by stkent** [comment]
Great work, all!

**Comment by stkent** [comment]
> As for where to put the hints, I definitely think it would be useful to have them somewhere. I don't think putting it in .meta/hints.md would be correct because I think that gets appended onto the readme. Is that right @stkent?

Agreed, notes for mentors should ideally live in the `.meta` directory (an exception: comments explaining why Java tests deviate from the canonical tests currently live inline in the test suites.)

**Comment by bmkiefer** [comment]
Given the notes that I previously wrote only help the mentors of track, do we even want to keep them in the repo? The problem specification somewhat outlines that the learners should be identifying the changes that they made to the code. If we want to forego using them, then we can merge this.

**Comment by FridaTveit** [comment]
I agree that since these are really notes for mentors, it doesn't really make sense for them to be kept in the repo. So I'm happy to merge this as is :)

What do you think @exercism/java?

**Comment by sjwarner-bp** [comment]
If that is what you think @FridaTveit I am happy to agree!

**Comment by stkent** [comment]
+1 we should figure out where to put mentoring resources (or wait for nextercism to drive a discussion along those lines) before including them.

**Pull request merged**
