### PR TITLE
isbn-verifier: updated tests and version file

### PR DESCRIPTION
**Pull request by aadityakulkarni**
isbn-verifier: updated tests and version file -> #1462

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by aadityakulkarni** [comment]
Thank you @sjwarner-bp, can we merge this now?

**Comment by sjwarner-bp** [comment]
Sorry @aadityakulkarni ! Got completely distracted, will merge now :slightly_smiling_face:

**Comment by sjwarner-bp** [comment]
Thanks for getting that done @aadityakulkarni :fireworks:

**Comment by aadityakulkarni** [comment]
Thank you @sjwarner-bp !

**Pull request merged**
