### PR TITLE
Added state-of-tic-tac-toe exercise

### LINKED ISSUE #2360: Implement new practice exercise: `state-of-tic-tac-toe`
The exercise `state-of-tic-tac-toe` has not been implemented yet for the Java track.
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/state-of-tic-tac-toe).

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise.
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR.

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem.

In case you have any further questions, feel free to ask here.

### PR DESCRIPTION
**Pull request by AniketNS**
Fixes #2360 

Hey @sanderploegsma, will you please check the code and tell me what changes I should make?

I'm a beginner so I took the help from chatGPT. Let me know if there is anything wrong.

### CODE REVIEW

**Review by sanderploegsma — CHANGES_REQUESTED** [review]
Before I do a full in-depth review, could you have a look at the failing GitHub Actions workflows for this PR? That should already provide you with some feedback to address. 

Once all workflows pass, I'll have a look at the full diff.

**Comment by AniketNS** [comment]
Sure I'll do that

**Comment by AniketNS** [comment]
Hey @sanderploegsma I went through the errors but most of the checks are about other practice exercises. I couldn't solve the issues. Will you please help me a little.

**Comment by sanderploegsma** [comment]
> I'm a beginner so I took the help from chatGPT.

I had a look at the CI errors as well as your implementation, and apart from some easy-to-fix issues my main problem is that some of the code you committed isn't valid Java. I can see that some of it must have been converted from Go using ChatGPT, but it didn't do a very good job, sorry.

To be honest, judging by the state of this PR I must say that contributing to the Java track may be a bit too early for you. We welcome contributions from the community, but since the platform is built to help others learn programming, I expect contributors to have a solid understanding of Java before they author complete new exercises.

So my suggestion is to start out with some smaller issues to work on instead. Otherwise, I'd advise you to work on your Java skills a bit more before picking up larger issues like these. I hope you understand.

**Comment by AniketNS** [comment]
Yeah @sanderploegsma, I did convert the Go code to Java with the help of chatGPT. Sorry for this behavior. I was trying to contribute but I should've done that with my knowledge. 

I'll work on my Java skills and then try to contribute to big issues like this. 

Thanks for the advice.

**Pull request closed without merging**
