### PR TITLE
Updating tests for poker exercise

### PR DESCRIPTION
**Pull request by jagdish-15**
# Pull Request

This PR updates all 11 unsynced tests for the Poker exercise, including 2 reimplemented tests and newly added tests to align with the problem-specifications repository.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by kahgoh** [comment]
The poker tests in the CI is failing. Does the example solution need updating?

```
Checking poker exercise...
poker: example solution did not pass the tests
```

**Comment by jagdish-15** [comment]
> The poker tests in the CI is failing. Does the example solution need updating?

I've updated the `Poker.java` file and its helper classes to ensure they pass the tests. However, I'm still unsure how to verify the changes locally using `configlet`. Could you guide me on that?

**Comment by kahgoh** [comment]
To run the tests locally, run `./gradlew test` from the exercises directory. For example:

```
# Start from where you clone the repo to
cd exercises
./gradlew test
```

If you want to run just the poker test, use `./gradlew practice:poker:test`. I also recommend running `./gradlew check` to run Checkstyle.

**Comment by jagdish-15** [comment]
Thank you so much, @kahgoh, for this! I truly appreciate your guidance—I wasn’t aware we could run these tests locally, and this has been incredibly helpful.

After testing the old reference answers on my local machine, I discovered that the initial reference implementation was failing five tests. Despite spending over two hours trying to understand the code, I found it overly complex and challenging to follow. A few days later, I attempted to use AI for assistance, but unfortunately, that approach also fell short.

Eventually, I realized I could explore community solutions for inspiration. While I didn’t immediately find a fully working solution, analyzing the approaches helped me iterate and improve. During this process, I identified several excellent alternatives that were far more efficient and readable compared to the original implementation. However, these solutions all failed a newly added test case.

This led me to uncover an oversight on my part—I had mistakenly marked the test as passed in the initial implementation. I sincerely apologize for this error. That said, since the original code was already failing four other tests, replacing it was necessary.

After further investigation, I selected the best community solution available, which resolved most issues. I also located the GitHub profile of the original contributor and have appropriately credited them as a contributor to the project.

[All tests have now been passed.]

Please let me know if you have any thoughts or feedback on this update!

**Review by kahgoh — APPROVED** [review]
The changes looks good now! Thanks!

**Pull request merged**
