### PR TITLE
Add topics to problem 'nth-prime'

### LINKED ISSUE #871: nth-prime: add topics
As part of the update to the exercism website, we want to add topics to each exercise. This should be topics that will most likely be relevant to the exercise even though you might be able to solve it without encountering that topic. There is a [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) used across all exercism tracks but you can add track specific ones as well if needed.

See issue #523 for a discussion about adding topics. There are also some exercises (e.g. hello-world and two-fer) that already have topics so you can look at them as examples. The topics need to be added to the entry for the relevant exercise in `config.json`.

Please comment on this issue or reference it in your pull request (using #issue-number) if you're going to be working on it. If you put "fixes #issue-number" in the pull request description then it will also automatically close this issue when the pull request gets merged :)

### PR DESCRIPTION
**Pull request by mhdsmr2**
Fixes #871.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by FridaTveit** [comment]
You've got a lot more commits in this review than you should have. You only want the last commit (4c0ed7f). To make sure you only have that commit in the PR there are a couple of options:
1. 
-- Close this review. 
-- Reset your master branch to the `exercism:master` branch to make sure it doesn't have any of your old work on it (`git checkout master`, `git fetch upstream`, `git reset --hard upstream/master`, assuming you've got your remote set up as `upstream` and that you have no work in progress on `master`). 
-- Make a new branch off master.
-- Cherry pick the commit you want from the old branch (`git cherry-pick 4c0ed7f`).
-- Push your changes.
-- Open a new PR for that branch.

2. 
-- Checkout this branch (`git checkout issue#871`).
-- Make sure you have the commit you want saved on another branch (e.g. by doing `git branch TempBranch` from your branch `issue#871`, thereby copying it).
-- Reset your branch to the `exercism:master` branch (`git fetch upstream`, `git reset --hard upstream/master`, assuming you've got your remote set up as `upstream`). 
-- Cherry pick the commit you want from the temporary branch (`git cherry-pick 4c0ed7f`).
-- Push your changes (you might have to use `git push -f origin issue#871` since you've reset your branch and are therefore rewriting history; to do that you need to use the force option while pushing).

To avoid this problem in future you should always keep your master branch up to date with the `exercism:master` branch and you should not put any other work on it. You should always fork your PR branches off your master branch so that they only new work on them is the commit(s) you want reviewed.

Does that make sense? Let me know if you need any help with that or you have any other questions :)

See [this guide](https://help.github.com/articles/fork-a-repo/#keep-your-fork-synced) on how to keep your fork synced :)

**Comment by mhdsmr2** [comment]
Should I close this PR?

**Comment by mhdsmr2** [comment]
I have a problem. When I am telling Git to push it to my changes it says my local repo is out-dated so I have to pull the changes that have been made to my Github repo. If I pull the changes, the old useless commits will come. Please help.

**Comment by mhdsmr2** [comment]
I got it. I am opening a new PR.

**Pull request closed without merging**
