### PR TITLE
Sync tests, file paths, metadata, and documentation with the problem-specifications repository

### PR DESCRIPTION
**Pull request by jagdish-15**
# Pull Request

This PR addresses the discussion initiated by the maintainer, @kahgoh, in [this issue](https://github.com/exercism/java/issues/2862).

This PR aims to synchronize all previously unsynced tests, file paths, metadata, and documentation with the **problem-specifications** repository.

### Proof of Sync

Screenshot 2024-11-17 132930

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Review by kahgoh — COMMENTED** [review]
I notice there are a number of `tests.toml` being synced here. I think we should revert the changes to `tests.toml` sync PR as the exercise's test haven't been updated. Some tracks have an test generator that you can run to re-generate or update the tests, but Java _isn't_ one of them ... so the tests need to be also be updated manually to match. 

Alternatively, we could also update the tests here. I'm not sure how trivial or big of a job updating the tests would be, but I'm happy for you to make the call whether to also update here or later in a separate PR.

**Comment by jagdish-15** [comment]
Yes @kahgoh, as mentioned earlier, there were tests.toml files that needed syncing. I wasn’t aware that test files require manual updates, but after your reply, I started manually updating the tests for each exercise. So far, I’ve completed 3 exercises and have 4 more to go. Once I finish, I plan to push changes for all 7 exercises together.

I wanted to clarify if I should add my name to the list of contributors for these exercises. While I’ve manually added tests based on the canonical-data file from the problem-specifications repo, this is more of a sync update. The last time I changed the reference solution and starting point for an exercise, I did add my name. Should I do so here as well?

Regarding the PR structure, I’m considering whether to handle everything in this PR or split it into multiple PRs. Keeping this PR focused on documentation updates and creating separate PRs for the test updates could make the changes more organized and easier to review. Additionally, while the work would remain the same, this approach might better align with contributing guidelines. Let me know your thoughts on the best approach.

**Comment by kahgoh** [comment]
For the contributors, yes, feel free to add yourself to the contributors list where you've updated the test as you're doing that manually. 

For the PR structure, I think splitting is a good option. In addition to keeping it organized, it also allows the Markdown file updates to go through while we do the test updates.

**Comment by jagdish-15** [comment]
I am hereby closing this PR as the other PRs discussed within it have already been raised.

**Pull request closed without merging**
