### PR TITLE
Remove references to gitter and replace them with references to the forum

### PR DESCRIPTION
**Pull request by andrerfcsantos**
Refer people to the forum instead of Gitter.

Since I think I'm the only active maintainer on the Java track, also requesting reviews from @ErikSchierboom and @exercism/reviewers.

### CODE REVIEW

**Comment by kotp** [comment]
Aparrently reviewers doesn't have the merge bit.

**Comment by andrerfcsantos** [comment]
> Aparrently reviewers doesn't have the merge bit.

That would explain why I wasn't able to formally request a review from exercism/reviewers. @ErikSchierboom Can you take a look at this?

**Comment by andrerfcsantos** [comment]
Superseded by #2190

**Comment by kytrinyx** [comment]
Sorry, I didn't think to check for an open issue; I just made issues on all the tracks.

**Comment by andrerfcsantos** [comment]
@kytrinyx No worries. I prefer someone else other than me opening PRs here in the Java track so the approval process is smoother, so thanks for making the PR :)

**Pull request closed without merging**
