### PR TITLE
Move from switch-statement to football-match-reports slug

### PR DESCRIPTION
**Pull request by mirkoperillo**
# pull request

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Review by ericbalawejder — APPROVED** [review]
I see the linter errors are addressed in #1911. Looks good. Is it valuable to fetch the changes from #1911 and run them against the linter again?

**Comment by mirkoperillo** [comment]
I think it's not necessary to merge #1911 into this branch, because the fixes on the linter are totally on other stuff (the linter fix is about some fields of configuration files outside the exercise folders).

**Comment by ericbalawejder** [comment]
I'm having some trouble resolving these conflicts.

**Comment by mirkoperillo** [comment]
@ericbalawejder, resolved the conflicts and aligned to the current main branch

**Pull request merged**
