### PR TITLE
Fix(config.json): change prereq of `cars-assemble` to `conditionals-if`

### LINKED ISSUE #2057: `cars-assemble` should have `conditionals-if` as a prerequisite
The exemplar file uses it, and I don't think it can be solved without it, a switch statement or crazy recursion

### PR DESCRIPTION
**Pull request by ynfle**
Closes #2057

# pull request

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by ynfle** [comment]
I'm pretty sure configlet failures are unrelated to this PR

**Comment by jmrunkle** [comment]
> I'm pretty sure configlet failures are unrelated to this PR

Yep: #2064

**Review by jmrunkle — APPROVED** [review]

**Comment by jmrunkle** [comment]
Unfortunately, cannot merge this until we get configlet lint working and then you will have to patch that fix into your branch.

**Comment by jmrunkle** [comment]
> Unfortunately, cannot merge this until we get configlet lint working and then you will have to patch that fix into your branch.

I stand corrected. I thought they had made configlet lint a hard requirement for merging changes into these repos.

**Pull request merged**
