### PR TITLE
Potential solve for #326 and journey-test passing when they fail

### PR DESCRIPTION
**Pull request by Smarticles101**
Not been tested much, but I believe that this should work

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by stkent** [comment]
Could you push a broken commit to test this, then revert once we see a failure as expected? That'd be an awesome test in real conditions if so! ❤️

**Comment by Smarticles101** [comment]
Tried setting the `.travis.yml` to set the build status to failed if one of the test suites fail, but it seems that the status stays at pending

**Comment by Smarticles101** [comment]
So I wrestled with getting the build to fail as soon as the first build fails. I found out this isn't possible after emailing support. 

> Thanks for writing in with your feature request. As things are right now, it is not possible to fail a build on the first job failure. It would, however, make sense, and we have reported it internally. This is no guarantee that this will be built.

I'll an issue about it on the travis-ci github about it.

**Comment by stkent** [comment]
Thanks for plugging away at this!

If I understand correctly, you're saying it's not currently possible, when using the Travis matrix stuff, to 'fail fast' as soon as one of the dimensions (e.g. unit tests) fails? Given that, what does the `trap 'exit 1' ERR` change buy us? Not asking because I don't believe it helps; I just don't know how and would appreciate the education :)

**Comment by Smarticles101** [comment]
> If I understand correctly, you're saying it's not currently possible, when using the Travis matrix stuff, to 'fail fast' as soon as one of the dimensions (e.g. unit tests) fails?

That is exactly what I'm saying.

> Given that, what does the trap 'exit 1' ERR change buy us? Not asking because I don't believe it helps; I just don't know how and would appreciate the education :)

It was added to the unit-tests because that allows for errors in subshells to be caught where as `set -e` doesn't. I added it to the run-journey-test-in-ci file because before I had forgotten to add any error handling. Bash defaults to ignore errors inside scripts, so this extra line will catch the error and exit with the exit code 1. Before, if the journey-tests failed, the run-journey-test-in-ci would exit with code 0 because bash was ignoring the error returned by the journey-tests

**Comment by stkent** [comment]
Awesome, thanks! So in the case of the journey tests, those now fail fast in the same way as the unit tests should? 💯 Anything preventing me from merging this as-is? :)

**Comment by Smarticles101** [comment]
Nope! I believe this is good right now. I'll continue to watch the builds over the next week or two

**Comment by stkent** [comment]
Sweet! :shipit:

**Pull request merged**
