### PR TITLE
Create a DO_NOT_IMPLEMENT.md file for java/leap

### PR DESCRIPTION
**Pull request by jmrunkle**
Add a DO_NOT_IMPLEMENT.md file to make it clear why we cannot implement this exercise. Part of #1589

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by jmrunkle** [comment]
If we decide to go this route, I would suggest that we need to change the CI code to allow this (and only this) for the exercises that should not be implemented.

**Comment by jmrunkle** [comment]
Looks like the error comes from the configlet that is a bit harder to change / ignore since it is used by many projects. Might have to have that discussion over in the configlet itself rather than directly in here.

**Comment by SleeplessByte** [comment]
I think this makes sense.

**Comment by jmrunkle** [comment]
Created https://github.com/exercism/configlet/pull/163 which I believe would allow this to work

**Comment by yawpitch** [comment]
The motivation for this ended with #1712 being merged in late July. See my comment [here](https://github.com/exercism/exercism/issues/4932#issuecomment-552202038).

**Comment by yawpitch** [comment]
Since exercism/exercism#4932 has been closed, this probably should be as well.

**Pull request closed without merging**
