### PR TITLE
sum-of-multiples: updated the version #1131

### PR DESCRIPTION
**Pull request by hgvanpariya**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sjwarner-bp** [comment]
Additionally, though this isn't mentioned in #1131, it looks like our test suite does differ from the canonical data. The test:

```
    {
      "description": "multiples of 3 up to 7",
      "property": "sum",
      "input": {
        "factors": [3],
        "limit": 7
      },
      "expected": 9
    },
```

in the canonical data is not in the Java test suite yet.

**Comment by hgvanpariya** [comment]
@sjwarner-bp , so Shall I update the version to 1.2.0 ?

**Comment by sjwarner-bp** [comment]
Yes, that's what we're after here. It's odd that we deviate from the canonical data here, but that's not mentioned in the issue (maybe someone else in @exercism/java can clarify) :slightly_smiling_face:

**Comment by FridaTveit** [comment]
That test case might have been added after I looked through all the exercises or I might just have missed it while looking through them. Either way it should probably be added to our tests 🙂 You could do that in this PR if you want @hgvanpariya? Or we could open a new issue for it if you would rather this PR was merged straight away 🙂

**Comment by hgvanpariya** [comment]
@FridaTveit , is it possible to merge this and share the new issue number ?

**Comment by FridaTveit** [comment]
Opnened issue #1253 🙂

**Comment by sjwarner-bp** [comment]
@FridaTveit Oops, you beat me to it! I also opened #1254 - I'll close it :wink:

**Pull request merged**
