### PR TITLE
Shape - Add new Exercise

### PR DESCRIPTION
**Pull request by laritzalba**
- Description: Create and draw geometric shapes in a windows/ panel.
			The objective of this exercise is to practice yours skill in object Oriented Programing (create classes, use heritance, polymorphism, etc).
- Source: Inspired from an exercise from a class of the University Catholic of Louvain
- Url Source: https://hdl.handle.net/20.500.12279/408

I’m adding this exercise directly in this track because the “problem-specifications” track is not accepting new exercises. (I asked here (#1740) before do this PR). 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by laritzalba** [comment]
Hi,
Can someone verify/ help me with this PR ? @FridaTveit

**Comment by laritzalba** [comment]
Hi,
Thank for your answer, at least you didn’t reject (close PR) directly, so I’ll wait for your consensus for this PR. Let me know your final decision as soon as you can  @exercism/java. 🙂

**Comment by FridaTveit** [comment]
Thank you for being so patient @laritzalba! 🙂

**Comment by laritzalba** [comment]
Hi, I was wandering if the team finally decide something about this PR, I know you are busy with a lot of stuffs, however if you have some news, it’ll be another happy person in this world . 🤪🥳
Have a nice day.  😇

**Pull request closed without merging**
