### PR TITLE
Sieve Update

### LINKED ISSUE #1134: sieve: update tests and add version file
The sieve tests should be updated to exactly match the canonical data. Also a version file should be added to match the canonical data version.

### PR DESCRIPTION
**Pull request by Kyle-P**
Added tests to match canonical data and added a version file.

Closes #1134 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sjwarner-bp** [comment]
Thanks for this one @Kyle-P :slightly_smiling_face:

**Comment by Kyle-P** [comment]
No problem @sjwarner-bp! Would you recommend deleting branches after they've been merged into master?

**Comment by sjwarner-bp** [comment]
I often delete branches that have been successfully merged in, as more often than not you won't need them again! :slightly_smiling_face:

**Comment by Kyle-P** [comment]
Alright, thanks @sjwarner-bp!

**Pull request merged**
