### PR TITLE
Change TestTrack.getRankedCars stub to take a list of cars, consistent with the unit tests

### PR DESCRIPTION
**Pull request by IsaacG**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sanderploegsma** [comment]
- Not sure why CI isn't picking this up, but the exemplar implementation in `.meta/src/reference/java/TestTrack.java` also contains the invalid method signature and should therefore be updated as well
- The code snippet in the instructions should probably be updated to match the new signature by passing it `unsortedCars`

**Review by iHiD — APPROVED** [review]
Blind approving for you :)

**Comment by IsaacG** [comment]
Thanks! I updated additional sites called out by @sanderploegsma

**Comment by sanderploegsma** [comment]
This also fixes #2330 and #2318 by the way

**Pull request merged**
