### PR TITLE
Sync docs

### PR DESCRIPTION
**Pull request by IsaacG**
# pull request

Sync the docs

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
Sometimes the docs (instructions) change together with new / other / changed tests, so I don't think it's smart to just sync all these without seeing if tests also need updating.

**Comment by sanderploegsma** [comment]
I agree, this PR is way too big to have a good idea of what needs syncing. I propose we tackle the exercises one-by-one, so that we can make sure the tests/stubs are still up-to-date with respect to the updated docs.

**Comment by IsaacG** [comment]
Is there interest in per exercise sync PRs? I can create them if someone wants to review them.

**Comment by sanderploegsma** [comment]
Yes, sure! I can review them.

**Comment by IsaacG** [comment]
> Yes, sure! I can review them.

PRs opened to sync the docs ... for A and B exercises :) I'll let you review/merge those before I carry on.

**Pull request closed without merging**
