### PR TITLE
Issue 803 fix

### PR DESCRIPTION
**Pull request by spmvanmierlo**
#822

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by FridaTveit** [comment]
Thanks for doing this fix @spmvanmierlo! :) Please could you push it to your previous pull request (#822)? You don't have to open a new PR for each fix, you can just push the commit with the fix to the same branch which you used to create the PR (in your case `spmvanmierlo:issue791`). The commit will then automatically get added to the PR :)

By creating a new PR instead it makes it harder for us to review it. Also you've added another commit which doesn't have anything to do with the PR (adding food chain topic). So this PR can't be merged with that commit in it.

So please push the fix commit to your other branch (`spmvanmierlo:issue791`) if that's okay :) Let me know if you have any problems :)

**Comment by spmvanmierlo** [comment]
@FridaTveit I am not sure how I can fix that at the moment.. not that kind of a git guru, sorry

**Comment by FridaTveit** [comment]
Are you using the command line (on something like git bash, linux terminal or mac terminal)? If so, try doing this:
`git checkout issue791` (will move you to the branch for PR #822)
`git cherry-pick 51054d7` (will add the commit fixing the spacing issue to that branch)
`git push origin issue791` (will push the new commit to PR #822, since that PR has been setup against the branch `issue791`)

Does that make sense? :)

**Comment by spmvanmierlo** [comment]
Just followed your steps :) , did it work?

Thanks for explaining! It does make sense :)

**Comment by FridaTveit** [comment]
Yes, it did work! Thanks for taking the time to do that! :)

**Pull request closed without merging**
