### PR TITLE
Acronym: Update version and add consecutive delimiter test

### PR DESCRIPTION
**Pull request by lemoncurry**
#1518 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by beatbrot** [comment]
@FridaTveit Actually, I was working on it :D 

But if this PR does the job, it's no problem, I'll just pick another Issue :)

On a side note: How do you think about creating Unit-Tests out of the canonical-data.json? 
I could work on that, If you want me to :)

**Comment by FridaTveit** [comment]
Thanks @beatbrot, that's very generous of you! 🙂 Sorry about the confusion!

You mean make an automatic test generator? That's an idea worth discussing, I've opened issue #1580 for it 🙂

**Comment by sjwarner-bp** [comment]
Hi @beatbrot - do you mean automatically generating the test suite from the canonical data?

**Comment by lemoncurry** [comment]
@beatbrot I am sorry, I didn't realize you were working on it 😟

**Comment by beatbrot** [comment]
No problem @lemoncurry :relaxed:

**Pull request merged**
