### PR TITLE
Add blurb to config.json

### LINKED ISSUE #759: Add blurb to config.json
In `config.json` we need to have a blurb which explains a bit about Java in ~30 words. See [the Go track's `config.json`](https://github.com/exercism/go/blob/master/config.json) for an example.

### PR DESCRIPTION
**Pull request by FridaTveit**
This is probably not the best description but it's better than nothing. Please feel free to offer suggestions for a better blurb/better grammar/better wording or anything! :)

Fixes #759.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by michaelspets** [comment]
Hey @FridaTveit,  I do not agree with this description. I would prefer instead what James Gosling would say: The Java programming language is a general-purpose concurrent class-based object-oriented programming language, specifically designed to have as few implementation dependencies as possible. It lets application developers "write once, run anywhere".

**Comment by FridaTveit** [comment]
Hi @michaelspets :) Like I said, I'm very happy to receive different suggestions for the blurb, thanks for offering your help! :)

As it is though, we've already had a complaint about the sentence "specifically designed to have as few implementation dependencies as possible." (see issue #406). Also bear in mind that the first thing the users will read after this blurb is [ABOUT.md](https://github.com/exercism/java/blob/master/docs/ABOUT.md) which starts with:
>Java is a general-purpose computer programming language that is:
>- Concurrent
>- Class-Based
>- Object-Oriented

But I guess whatever we write it will probably be repeated somewhere in `ABOUT.md`. Later in `ABOUT.md` it mentions low-level features and being simple as well. So repetition might be unavoidable/not a problem?

Also from what I can tell this is taken word for word from Wikipedia. I think @kytrinyx wanted us not to directly quote something like Wikipedia but instead use our own phrasing to make it more understandable, but I may have got that wrong?

What do you think @exercism/java?

**Comment by stkent** [comment]
I think the implementation dependencies line is confusing, especially for newcomers. The "write once, run anywhere" portability is probably something worth calling out, however. I'd be in favor of adapting that and including it in the blurb somehow.

**Comment by FridaTveit** [comment]
I tried to incorporate the portability in the blurb. What do you think @stkent, @michaelspets? :)

**Comment by michaelspets** [comment]
It is very nice @FridaTveit.

**Comment by stkent** [comment]
Perfect mashup!

**Comment by Smarticles101** [comment]
LGTM!

**Comment by kytrinyx** [comment]
>  I think @kytrinyx wanted us not to directly quote something like Wikipedia but instead use our own phrasing to make it more understandable

Sorry I'm so late to this.

Yes—I don't want us to quote Wikipedia or other sources directly, unless it's a really great colloquial, friendly quote, and then only if we have it in the ABOUT with proper attribution. The blurb is not the place for this.

Thanks @FridaTveit for taking the lead on getting this done, and thank you @michaelspets for your input. It's only by actually raising the issue that we can discuss these things and figure out what works for our situation.

**Pull request merged**
