### PR TITLE
Fix missing exemplar paths in concept exercises

### LINKED ISSUE #1885: Linter checks failure
Currently the checks of a submitted PR fail.
In detail the configlet linter phase fails.
An example of failure output
  ```  
   Array is empty: 'files.exemplar':
   /home/runner/work/java/java/exercises/concept/interfaces/.meta/config.json
```
The problem is that `config.json` file contained into every concept exercises should
explicitly define the path of the reference solution into the files.exemplar field

Taking as example the failure message

Exercise `interfaces` should contains this

``` 
  "files": {
    "solution": [
      "src/main/java/ExperimentalRemoteControlCar.java",
      "src/main/java/ProductionRemoteControlCar.java",
      "src/main/java/RemoteControlCar.java",
      "src/main/java/TestTrack.java"
    ],
    "test": ["src/test/java/RemoteControlCarTest.java"],
    "exemplar": [
	  ".meta/src/reference/java/ExperimentalRemoteControlCar.java",
	  ".meta/src/reference/java/ProductionRemoteControlCar.java",
	  ".meta/src/reference/java/RemoteControlCar.java",
	  ".meta/src/reference/java/TestTrack.java"
    ]
  }
```

### PR DESCRIPTION
**Pull request by mirkoperillo**
Try to fix configlet checks errors

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by mirkoperillo** [comment]
@msomji @ericbalawejder I need a review.
This fixes a lot of configlet checks errors, then we need to decide tags for the track (#1890) to fix what seems to remain

**Comment by ericbalawejder** [comment]
Ok, I see. The only error relates to the "tags" array referenced in #1890. Looks good.

**Review by ericbalawejder — COMMENTED** [review]
Looks good.

**Comment by mirkoperillo** [comment]
@ericbalawejder it seems you haven't approved explicitly the PR, so I cannot merge it

**Review by ericbalawejder — APPROVED** [review]

**Comment by ericbalawejder** [comment]
Apologies.

**Pull request merged**
