### PR TITLE
Fix typo in the Dig Deeper text for Grains

### PR DESCRIPTION
**Pull request by nomicos**
Fixed the wrong power of two that gives us 8.
https://exercism.org/tracks/java/exercises/grains/dig_deeper

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by bobahop** [comment]
Good catch! This is probably in all the other Grains approaches I've done for other tracks...

**Comment by nomicos** [comment]
@bobahop Is there a centralised place where this text can be amended? If not, I would be happy to have this contribution approved at least for the Java track; and then the mistake can be fixed in other repositories 🙂

And thank you for all the work you put into these articles!

**Comment by bobahop** [comment]
@nomicos : thanks, but there is no centralized place, so I've already made PRs for the other tracks, some of which have already been approved.

**Comment by andrerfcsantos** [comment]
Closing and reopening to refresh CI.

**Review by andrerfcsantos — APPROVED** [review]
@nomicos Thanks!

**Pull request merged**
