### PR TITLE
phone-number add hints and regenerated README.md file

### PR DESCRIPTION
**Pull request by c-thornton**
Added hints.md file and regenerated the README.md file with configlet.
Fixes issue #1086 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by c-thornton** [comment]
So not exactly sure why the build failed. It looks like it tried to download ruby-2.2.5 and that filed so the build failed. Can someone please provide some guidance for me on this one? Thanks.

**Comment by FridaTveit** [comment]
Thanks @c-thornton! :)

**Comment by c-thornton** [comment]
Thanks @sjwarner-bp and @FridaTveit. Just wanted to double check if I did something wrong. If this happens in the future is there a way that I can kick off the build again or is that something that you will have to do?

**Comment by sjwarner-bp** [comment]
No, nothing you've done wrong - we've just had a little bit of a problem with getting Travis to play nicely at the minute... Basically, it just seems to be timing out occasionally!

I'm not too sure if you will be able to kick the builds off again, or if it is something that can only be done by @exercism/java - but we're normally around so it shouldn't be too much of an issue :slightly_smiling_face:

**Comment by FridaTveit** [comment]
I'm pretty sure builds can only be kicked off by maintainers. You should be able to look at the output of the build though (by following the details link where it says the build failed). So you can use that to check why it failed. But if you don't understand why it failed or you think it's not your fault (e.g. it's because of timeout issues) then you can ping exercism/java or one of us and we should get round to kicking off the build again pretty quickly 🙂

**Comment by c-thornton** [comment]
Awesome, thanks @sjwarner-bp, I appreciate it. I will probably be picking away at some of the other issues that are similar to this as well. Though I don't want to take all of them so that others to get in on the fun and have some easier issues to get their feet wet as well.

@FridaTveit I figured I probably would not be able to kick off the build again, just wanted to see if I missed something that I should have seen. I have been known to miss obvious things that were staring me right in the face before.

**Comment by sjwarner-bp** [comment]
Help yourself to any open issues @c-thornton, it is always nice to see people getting involved! :slightly_smiling_face:

**Pull request merged**
