### PR TITLE
[WIP] Implement suggestions from #410

### LINKED ISSUE #410: Speed up test suite(s)
The CI build is approaching 20 minutes.  The long pole on the build is (understandably) the journey suite.  However, the exercises are guaranteed to be independent: the test suites can be executed in parallel without fear of test pollution.  The situation is ripe for parallel execute of tests.

Please update the CI build to minimize both the duration of the total test run _and_ minimize additional added complexity (i.e. readability of the build scripts themselves is paramount).

### PR DESCRIPTION
**Pull request by Smarticles101**
I'm going to use this pr to finish off the ideas to speed up the travis build. Should close #410 once I'm done.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by Smarticles101** [comment]
Made lots of mistakes but now it works. :smile: The journey-test script supports testing exercises given as parameters and `run-journey-test-from-ci.sh` pulls the modified exercises from the pull request to test only those exercises. I'll try investigating #326 tomorrow :) In the meantime, how does this look @exercism/java and @kytrinyx?

**Comment by kytrinyx** [comment]
This seems reasonable to me! I'd say let's try it.

**Comment by stkent** [comment]
@Smarticles101 I suggest that you merge this whenever you have a few days to monitor in case anything hiccups :)

**Comment by Smarticles101** [comment]
@stkent awesome, got it :)

**Pull request merged**
