### PR TITLE
[Allergies] Small simplification

### PR DESCRIPTION
**Pull request by michael-berger-FR**
Bit wise AND oeprator is used to check if the person is allergic to a given allergen.
If the result is different from 0, this is the case.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by michael-berger-FR** [comment]
> Thank you @michael-berger-FR

Hi @lemoncurry , thanks to you! :-)

**Comment by michael-berger-FR** [comment]
Hum, @lemoncurry , who will be doing the merge?

**Comment by lemoncurry** [comment]
@michael-berger-FR  sry I wanted to wait a bit for opinions of other maintainers, but I think I just merge it now. Thank you again! :smile:

**Comment by michael-berger-FR** [comment]
> @michael-berger-FR sry I wanted to wait a bit for opinions of other maintainers, but I think I just merge it now. Thank you again!

@lemoncurry , there was no hurry... I just wanted to understand the whole process. Anyway, thank you!

**Pull request merged**
