### PR TITLE
Fix codon spelling in Protein Translation README.md

### PR DESCRIPTION
**Pull request by piepero**
There was a misspelled STOP codon in the readme of the Protein
Translation exercise.

The spelling has been corrected and the exercise version number has
been increased.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by piepero** [comment]
Thanks for the info. :smiley:
I have created a new pull request, as requested:
https://github.com/exercism/problem-specifications/pull/1167

**Comment by sjwarner-bp** [comment]
Perfect! Once that's been discussed and merged (sometimes problem-specifications can move a little slower than the language tracks) we can fix up our copy as well :slightly_smiling_face: 

For the time being, I'll close this PR :+1:

**Comment by FridaTveit** [comment]
Great, thank you @piepero! 😃

**Comment by piepero** [comment]
You are welcome, @FridaTveit, and my thanks to everyone involved for making my first GitHub pull requests, however trivial the change may have been, a nice experience. 😊

**Pull request closed without merging**
