### PR TITLE
removed the reference to UnsupportedOperationException in instructions

### PR DESCRIPTION
**Pull request by unfirthman**
# pull request remove the reference to UnsupportedOperationException in instructions #2151 

I deleted lines 52 - 59 in [java/exercises/practice/hello-world/.docs](https://github.com/exercism/java/blob/9abbe2a744625d698691249714d992fbdc17662c/exercises/practice/hello-world/.docs/instructions.append.md?plain=1#L52-L59)

## This is to solve issue #2151 

Thanks @andrerfcsantos for the issue assignment! Always happy to contribute to building Exercism. 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Review by andrerfcsantos — CHANGES_REQUESTED** [review]
Thanks for this.

Here we probably still want to have a step 1, but we shouldn't mention exceptions at all in the text. This step 1 can just say that the student has to modify the solution file provided just so the function returns "Hello, World." and show the example that it is at the end of step 1 currently.

The title of the new step 1 can be something like `Fix the solution`

**Comment by unfirthman** [comment]
Understood. I will make these changes tomorrow and resubmit.

Thank you!

**Review by unfirthman — COMMENTED** [review]
# Edit 1

## Remove reference to UnsupportedOperationException in instructions #2153 

### Also fixed Step 1 instructions per previous comment @andrerfcsantos 

Thank you with your patience! I believe this should be closer to what we are looking for.

My newest commit aims to clarify expectations in Step 1:

New commit: 23218428602a4b95e3d8434d386e90be8a8c0655

**Comment by unfirthman** [comment]
Hello @andrerfcsantos  - just checking in. Did you have a chance to look over this next edit? No rush!!!

**Review by andrerfcsantos — APPROVED** [review]
Sorry for the delay in reviewing this.

There was just one place where the exception was being referred, but since it was a simple final fix, I just did it for you.

Thank you for this!

**Pull request merged**
