### PR TITLE
Expose all files in online editor

### PR DESCRIPTION
**Pull request by artamonovkirill**
# pull request

As per discussion here: https://github.com/exercism/java/issues/2157#issuecomment-1295851262

There are some classes that are not visible in the online editor, making it hard to solve it and causing obscure compilation errors if the student re-declares the class.

PR content:
- extra files exposed as read-only via editor
- a script to check missing files

Further possible actions:
- include the script into CI workflow
- since the script is pretty generic already, it can probably be used in other tracks too after minimal modifictions
- check for orphan files in `config.json`

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Review by andrerfcsantos — APPROVED** [review]
Thanks!

**Comment by artamonovkirill** [comment]
I guess not all of the files in this PR are good in `editor` section. E.g., `error-handling`:
Screenshot 2022-11-12 at 20 46 28

Is there some generic way I can find ones that need moving to `solution`? E.g., containing `UnsupportedOperationException`?

**Comment by andrerfcsantos** [comment]
@artamonovkirill Maybe we can check for the `UnsupportedOperationException` to consider files that should go into the `solution` key.

**Comment by artamonovkirill** [comment]
Looks like it was the only exercise, created https://github.com/exercism/java/pull/2206

**Pull request merged**
