### PR TITLE
word-search: updated version file(v1.2.0 -> v1.2.1) #1473

### PR DESCRIPTION
**Pull request by miranikaran01**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by miranikaran01** [comment]
Hi,
I'm sorry for creating this pull request. Could someone please explain what went wrong?

**Comment by sjwarner-bp** [comment]
Hi @miranikaran01!

The TravisCI build failed - if we check the logs we can see:

```
+echo '<<< assert_ruby_installed()'
<<< assert_ruby_installed()
+make_local_trackler /home/travis/build/exercism/java/build/trackler /home/travis/build/exercism/java/build/x-api
+local trackler=/home/travis/build/exercism/java/build/trackler
+local xapi_home=/home/travis/build/exercism/java/build/x-api
+echo '>>> make_local_trackler(trackler="/home/travis/build/exercism/java/build/trackler", xapi_home="/home/travis/build/exercism/java/build/x-api")'
>>> make_local_trackler(trackler="/home/travis/build/exercism/java/build/trackler", xapi_home="/home/travis/build/exercism/java/build/x-api")
++pwd
+local track_root=/home/travis/build/exercism/java
+pushd /home/travis/build/exercism/java/build/trackler
~/build/exercism/java/build/trackler ~/build/exercism/java
++sed 's/)//'
++sed 's/.*(//'
++grep -m 1 trackler /home/travis/build/exercism/java/build/x-api/Gemfile.lock
+local version=2.2.1.169
+git checkout v2.2.1.169
error: pathspec 'v2.2.1.169' did not match any file(s) known to git.
+on_exit
+echo '>>> on_exit()'
>>> on_exit()
+[[ '' != '' ]]
+cd /home/travis/build/exercism/java
+echo '<<< on_exit()'
<<< on_exit()
The command "$SCRIPT" exited with 1.
```

That's a really odd log - it looks like it can't quite find a certain version of a file we need (but should be there)!

But your PR looks just fine! It's exactly what I would have expected :slightly_smiling_face:

**Comment by miranikaran01** [comment]
@sjwarner  Thank you so much for the clarification! I'm sorry I deleted the original fork because I thought  this issue was created because of the fork.

**Comment by miranikaran01** [comment]
@sjwarner-bp  How should I resolve this?

**Comment by sjwarner-bp** [comment]
@miranikaran01 That's ok! It's always great to get contributions :slightly_smiling_face: 

I think that because the original fork has been deleted, the best way to do this will be:

- Re-fork the repo!
- Implement your fix!
- Create a PR! (It'll probably have to be a new one, as this PR won't re-attach to your new fork)
- Keep your fingers crossed that CI doesn't randomly error this time! (Don't worry if it does - the maintainers will be able to either kick it off again or advise on any errors)

You've already gone through all of this perfectly one time :slightly_smiling_face:

**Comment by miranikaran01** [comment]
@sjwarner-bp I'm excited to learn from & contribute to this community :) I'll fix the issue as soon as I can.

**Pull request closed without merging**
