### PR TITLE
Sync tests for practice exercise ``markdown``

### PR DESCRIPTION
**Pull request by manumafe98**
# pull request

This issue addresses: [#2388](https://github.com/exercism/java/issues/2388)

The goal is to sync the tests of the markdown practice exercise

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by manumafe98** [comment]
I guess to solve the tests failing I should update this function

https://github.com/exercism/java/blob/56b0d792aea56904e0053a63e45b4819fa33162e/exercises/practice/markdown/src/main/java/Markdown.java#L43

So if the count is greater than 7 to output the input but in a paragraph, right?

**Review by sanderploegsma — APPROVED** [review]

**Comment by sanderploegsma** [comment]
> I guess to solve the tests failing I should update this function
> 
> https://github.com/exercism/java/blob/56b0d792aea56904e0053a63e45b4819fa33162e/exercises/practice/markdown/src/main/java/Markdown.java#L43
> 
> So if the count is greater than 7 to output the input but in a paragraph, right?

Yes, but don't update the one in `src/main/java`, update the one in `.meta/src/reference/java` instead. The former is the stub file received by students, the latter is the reference implementation.

**Comment by manumafe98** [comment]
Yeah I was going to update that one as well, but the goal of the exercise is that passes all test and students reformat the code, that's why I thought on updating ``src/main/java``.

**Comment by sanderploegsma** [comment]
> Yeah I was going to update that one as well, but the goal of the exercise is that passes all test and students reformat the code, that's why I thought on updating ``src/main/java``.

Ah yes that's right, I forgot that this is a refactoring exercise. In that case you have to update both indeed. Sorry for the mixup!

**Review by sanderploegsma — CHANGES_REQUESTED** [review]
As discussed the `src/main/java/Markdown.java` file needs to be updated to reflect the new behavior as well.

**Review by sanderploegsma — APPROVED** [review]
Thanks! 🙏

**Pull request merged**
