### PR TITLE
Add hints to exercises without starter implementation

### PR DESCRIPTION
**Pull request by FridaTveit**
As exercises with difficulty 5 are the first exercises without starter implementation, they should have a hints file explaining how to fix the compiler errors that occur when an exercise doesn't have any starter
implementation.

This should be detailed in the policies doc.

I thought I would add the file to only one exercise until it's been reviewed so that I don't have to make changes to lots of files :) After the contents of the file has been agreed I could add the other files, or we could open good first patch issues to add them.

Fixes issue #1075.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by FridaTveit** [comment]
Do you think it's worth making good first patch issues for copying the file to the other difficulty 5 exercises? We only have one good first patch issue open so I think that could be a good idea. What do you think @sjwarner-bp?

**Comment by sjwarner-bp** [comment]
That's a good idea @FridaTveit - I think that they'd make good first patches, and it will give us a few more issues for easier onboarding! 🙂

**Comment by FridaTveit** [comment]
Great, I'll do that then :) And I think I need to regenerate the README for flatten-array now that I've added a hints file. Will do that too :) I do need to do that don't I @stkent?

Do you think that will make adding these files too difficult for a `good-first-patch` issue? Or will it be okay if we give very specific instructions for what they need to do to generate the readme? What do you think @stkent @sjwarner-bp?

**Comment by sjwarner-bp** [comment]
I think that with clear enough instructions this should be an easy enough patch, and will introduce new contributors to a different set of tools (i.e. configlet) than they might otherwise be exposed to :slightly_smiling_face:

**Comment by FridaTveit** [comment]
Cool, update this review with the fixed readme and as soon as this is merged I'll start making good first patch issues :)

**Comment by sjwarner-bp** [comment]
Thanks for doing this @FridaTveit :slightly_smiling_face:

**Pull request merged**
