### PR TITLE
Switch to AssertJ (#2147)

### PR DESCRIPTION
**Pull request by keszocze**
# pull request

Use AssertJ in more exercises.  Might be in partial conflict with #2511 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sanderploegsma** [comment]
Thanks for opening this PR! Next to the conflicts with #2511 which was merged I also see that you're including a lot of commits that have been merged as part of other PRs in the last weeks, causing the diff to be way larger.

Looking at the latest commits I see you updated these four exercises, correct?

1. Diffie Helman
2. DnD Character
3. Zipper
4. Change

I believe that 2. and 4. have been resolved by #2511 and 1. is actually a deprecated exercise (which we don't update anymore). That just leaves 3.

Could you maybe open a new PR that just updates the Zipper exercise? I suggest making sure that the `main` branch of your fork is up-to-date with our `main` branch and creating a new branch from there. You can then either cherry-pick the commit(s) updating the Zipper exercise, or make the changes again manually and commit those. That's up to you.

**Comment by keszocze** [comment]
Sure can do. I simple re-used the branch that I used for the previous PRs. I didn't expect the already merged commits to pop up again.

Just two questions:
* Should I omit the Diffie Helman change? 
* How many exercises should I touch in a single PR?

**Comment by sanderploegsma** [comment]
> Sure can do. I simple re-used the branch that I used for the previous PRs. I didn't expect the already merged commits to pop up again.

Yeah we use 'squash and merge' on PRs so all commits get collapsed into one. That unfortunately means that you'd have to rebase existing branches to get the history correct. Easiest is to always start fresh!

> Just two questions:
> 
> * Should I omit the Diffie Helman change?

Yes. [Deprecated exercises are not supposed to be touched after deprecation](https://exercism.org/docs/building/tracks/deprecated-exercises), so no update needed there.

> * How many exercises should I touch in a single PR?

There's no strict guidelines on that, but since every change to an exercise's Java code triggers new test runs of submitted solutions the answer is "not too many". I'd personally aim for no more than 10-20, to also keep the PRs relatively small and easy to review.

**Comment by sanderploegsma** [comment]
Oh I'm sorry, I just double-checked and apparently I misspoke: the Dnd-Character and Change exercises weren't updated in #2511. I just assumed they were because of the merge conflicts.

In that case, I'd still open a new PR but feel free to include those exercises as well!

**Pull request closed without merging**
