### PR TITLE
Retire as maintainer

### PR DESCRIPTION
**Pull request by lemoncurry**
Due to life changes in the last few months and the very limited time to contribute I retire from maintaining the Java-Track. I thought about retiring for the last few weeks and am happy and relieved that there will be new maintainers to this track to take over, with more time on their hands.

I am very grateful for the opportunity to learn about maintaining a track. I especially want to thank @FridaTveit who was the best example I could have wished for as a maintainer. I learned so much from @FridaTveits way to review PRs and her always polite and helpful way of communication.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by FridaTveit** [comment]
That's so lovely to hear @lemoncurry 🙂 Thank you for all your great work, you were a pleasure to work with! 🙂

**Comment by ErikSchierboom** [comment]
Thanks for everything you did @lemoncurry!

**Comment by ErikSchierboom** [comment]
Any Java maintainer: feel free to merge this.

**Comment by iHiD** [comment]
@lemoncurry Thanks for all your effort! Please feel welcome back any time in the future :)

**Comment by kytrinyx** [comment]
@lemoncurry Thank you so much for all that you've given to Exercism over the years! Good luck with your next steps and projects ❤️ 💛 💚 💙 💜 🖤

**Pull request merged**
