### PR TITLE
Add exercise 'leap'

### PR DESCRIPTION
**Pull request by lemoncurry**
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by lemoncurry** [comment]
Ok, I just saw through failed Travis CI build that this exercise is not supposed/allowed to be implemented for Java.

What led to this decision, since the exercise is offered in other languages, e.g. exercism/Python?

**Comment by FridaTveit** [comment]
Issue #3 should explain it:

> These exercises were inspired by Java Ranch and are not allowed to be implemented.

Does that make sense @lemoncurry? 🙂 Thanks for wanting to contribute! 🙂

**Comment by lemoncurry** [comment]
I see. Thank you for your answer @FridaTveit !

**Comment by FridaTveit** [comment]
No problem 🙂 It is a bit confusing, I had to search through the issues to find out why it couldn't be implemented. I've raised issue #1589 to discuss how we can make it more obvious! 🙂

**Pull request closed without merging**
