### PR TITLE
Move from interfaces to remote-control-competition slug

### PR DESCRIPTION
**Pull request by mirkoperillo**
# pull request

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by mirkoperillo** [comment]
I have noticed the new linter check. It is about the required name field in a concept exercise config something like this
```
 {
           "slug": "lasagna",
           "name": "Cook your lasagna",   <----
            "uuid": "01924e92-ecc7-4ba6-83f9-f142c0756b9f",
            "concepts": [
              "basics"
            ],
           "prerequisites": [],
           "status": "wip"
         },

```
We are already solving this for every exercise during the slug renaming.
So please accept the PR. The linter error will be fixed with the last 2 slug renaming (constructors and classes exercises)

**Comment by mirkoperillo** [comment]
@ErikSchierboom please can approve this PR to unblock me :pray: ? 
thank you a lot

**Review by ericbalawejder — APPROVED** [review]
I'm not sure why the linter error says name key is missing?

**Comment by mirkoperillo** [comment]
@ericbalawejder I think it's a new check rule.
The name fields are missing in the some other concept exercises.
Looking this PR the linter warns about 4 missing keys and looking the `config.json` of this PR I found these:
https://github.com/exercism/java/blob/75a980c7129b65052eefb8dc396f923e0a814806/config.json#L58
https://github.com/exercism/java/blob/75a980c7129b65052eefb8dc396f923e0a814806/config.json#L83
https://github.com/exercism/java/blob/75a980c7129b65052eefb8dc396f923e0a814806/config.json#L108
https://github.com/exercism/java/blob/75a980c7129b65052eefb8dc396f923e0a814806/config.json#L184

**Pull request merged**
