### PR TITLE
parallel-letter-frequency: Rename hints file to match convention

### PR DESCRIPTION
**Pull request by kytrinyx**
The file in `.meta` should be named all lowercase letters.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by kytrinyx** [comment]
Since this is purely janitorial and not Java-specific I'm going to go ahead and merge this as soon as the build passes.

**Comment by sjwarner-bp** [comment]
I think this is already being solved in #1218

**Comment by kytrinyx** [comment]
No, this is a different issue. The linked PR is for a `version` file. This exercise has a `HINTS.md` rather than a `hints.md` (note that all the other exercise in the track correctly use the lowercase `hints.md` filename).

**Comment by kytrinyx** [comment]
Ah, you were pointing to a different issue. Yes, you're right. It's the same one.

**Comment by sjwarner-bp** [comment]
Must have been a typo - was on mobile 🙂

**Pull request merged**
