### PR TITLE
Fix journey test

### LINKED ISSUE #1063: Travis CI build intermittently failing
The Travis CI build is intermittently failing, and often requires a manual restart in order to get a green build.

When it fails, the same error message is seen:

```
+echo ==================================================
==================================================
+echo 'Solving settings.gradle'
Solving settings.gradle
+echo ==================================================
==================================================
+./exercism --config .journey-test.exercism.json fetch java settings.gradle
127.0.0.1 - - [30/Nov/2017:08:15:43 +0000] "GET /v2/exercises/java/settings.gradle HTTP/1.1" 200 339 0.0072
Not Submitted:         1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
New:                   1 problem
java (Settings.gradle) /home/travis/build/exercism/java/build/exercism/java/settings.gradle
unchanged: 0, updated: 0, new: 1
+cp -R -H '/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*' /home/travis/build/exercism/java/build/exercism/java/settings.gradle/src/main/java/
cp: cannot stat ‘/home/travis/build/exercism/java/exercises/settings.gradle/.meta/src/reference/java/*’: Not a directory
```

Most recent examples of PRs that have been affected by this behaviour are #1060 and #1004.

### PR DESCRIPTION
**Pull request by FridaTveit**
Attempt to fix #1063. Includes temporary commit to check that it's working (changing something in settings.gradle to make sure the script doesn't try to run settings.gradle like an exercise)

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/xjava/blob/master/POLICIES.md#event-checklist)

### CODE REVIEW

**Comment by sjwarner-bp** [comment]
I'm liking the look of this! I think that it would be great to merge in if it works 🙂 

I'd be interested in merging this too, as I've never squashed and merged before and would like to make sure I'm doing it correctly 😃

**Comment by bmkiefer** [comment]
LGTM!

**Comment by sjwarner-bp** [comment]
Thanks @FridaTveit , and great work everyone!

**Comment by stkent** [comment]
Wonder why we don't see the `build.gradle` file pulled in erroneously also?

**Comment by bmkiefer** [comment]
Does it not get pulled in when it is changed? The way that it is written it would lead me to believe that it would cause a CI failure if the build.gradle in the exercises folder changed. The most recent change that was merged on the build.gradle suffered from the Github API limit failure that caused the whole test suite to run and complete, [here](https://github.com/exercism/java/pull/770). Which is probably why this didn't put up then.

**Comment by stkent** [comment]
That was my hypothesis also!

**Pull request merged**
